### PR TITLE
Allow nesting via option, fix deprecation

### PR DESCRIPTION
**Pull request by jacobp100**

### CODE REVIEW

**Comment by davidtheclark** [comment]
Nice. I don't think it needs to be behind an option, since it's not destructive, right? Anybody who's using nesting would expect it to work, and people who aren't using nesting wouldn't care.

In order to finish the PR it will need documentation and tests.

**Comment by jacobp100** [comment]
~~Not sure, it requires another plugin to get it to actually work, which is clearer if you opt-in. Your call.~~

I think it would be a breaking change to enable this by default.

**Comment by davidtheclark** [comment]
> I think it would be a breaking change to enable this by default.

Why? What situation would break?

**Comment by jacobp100** [comment]
If they nested before, it was removed from the code. Now it isn't. If the new code is passed to a minifier or something like that, it could break the pipeline.

**Comment by davidtheclark** [comment]
OK, makes sense. I still think we should not hide this behind an option, though. If we need a major release, let's do that.

**Comment by pietrofxq** [comment]
@davidtheclark can you merge this?

**Comment by davidtheclark** [comment]
> I still think we should not hide this behind an option, though. If we need a major release, let's do that.

@pietrofxq: That was the outstanding issue here. I'd rather just release a breaking change. I'm going to close this PR due to inactivity; but if you'd like to create a new one based off it that's not behind an option I'll merge that!

Also, @pietrofxq, I don't use this package any more ... would you like to take over maintenance of it?

**Pull request closed without merging**
